### ISSUE TITLE
Callid

### ISSUE THREAD

**Issue by zadcall** [voximplant/flutter_callkit#1]
Is there is any way to get the call id from the push notification payload ?! @VladimirBrejcha

**Comment by VladimirBrejcha** [comment]
hi @zadcall,
This plugin is designed to work with CallKit and it does support incoming call push handing. 
You should use reportNewIncomingCallWithUUID method in iOS code and after that you can get the CXCallUpdate you passed to it in your dart code via didDisplayIncomingCall callback.
This is where you can get CXCall uuid (Note: callKitUuid and callId is not the same thing. СallKitUuid is used by CallKit framework, but callId is managed by Voximplant framework). Regarding other parts of push handling (registering tokens or receiving payload) - it is not included, so to deliver payload into dart code you might want to use something else (for example flutter_voip_push_notification plugin). 
About Voximplant Flutter SDK integration - once you reported payload to VIClient and successfully logged in, you'll receive didReceiveIncomingCall callback with VICall instance (including callId).
We're working on pushes + callkit integration to flutter Voximplant demo apps and it will be available soon

**Comment by zadcall** [comment]
@VladimirBrejcha Thanks for your reply, I already managed to make the push notification work when the app is closed with the demos, but in android when I open the application from the push notification, it doesn't open the incoming call screen, and I tried to open it manually after the application is initiated and now its working successfully, but when I click answer, it shows that its in another thread with another callId, finally I tried to get the callId manually so I can send it to incoming call screen manually, but I didn't found a way to get it, also when I call onIncomingcall its not returning anything, and the same for the Icall.

I hope you can just tell me what I can do here.

**Comment by VladimirBrejcha** [comment]
It seems like an app bug, if you using Voximplant demo apps and face these issues - please open the issue in the demo repository and provide following information there:
1. steps to reproduce
2, Device and OS
3. Logs from the app
