### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by VictorUvarov** [voximplant/flutter_callkit#10]
Flutter stable now supports sound null safety and this package has conflicts with `uuid: ^3.0.1`.

Is there a way to remove the uuid since it is only used in the example? Is it possible to move the `uuid` to `dev_dependencies`

**Comment by VladimirBrejcha** [comment]
@VictorUvarov thank you for the report. The problem now should be resolved in v1.2.0+4!

**Comment by VladimirBrejcha** [comment]
@VictorUvarov planned!

**Comment by VladimirBrejcha** [comment]
@VictorUvarov 2.0 with null safety just released!
