### ISSUE TITLE
Caller Identification

### ISSUE THREAD

**Issue by acamenhas** [voximplant/flutter_callkit#13]
First of all, many thanks for your effort in this library!

It's possible to identify the caller number (from landline or mobile number) or CallKit only works for voip applications?

Thank you

**Comment by VladimirBrejcha** [comment]
Hey @acamenhas ,

That is not clearly said in the docs, however, from my tests - Call Directory works perfect with mobile numbers from incoming calls (any calls, not just your app), but works not that good with voip app calls (some may be not identified or not blocked)

**Comment by acamenhas** [comment]
> Hey @acamenhas ,
> 
> That is not clearly said in the docs, however, from my tests - Call Directory works perfect with mobile numbers from incoming calls (any calls, not just your app), but works not that good with voip app calls (some may be not identified or not blocked)

Hi @VladimirBrejcha,
Many thanks for your answer.
