### ISSUE TITLE
How to create an outgoing call from the recent calls list.

### ISSUE THREAD

**Issue by kostasoft** [voximplant/flutter_callkit#18]
Thank you very much for the great implementation of the plugin.  Beautiful clean code. I really like it.
I still have one problem: I can't figure out how to get the event that occurs when I click on the last calls list item in my phone?  This list includes all my voip calls that were made through my app using your plugin (were registered in CallKit).
Clicking on the saved call just opens my app, and I would like to initiate an outgoing call (audio or video, depending on the previous call) in my app.

rus: 
Спасибо, большое за отличную реализацию плагина.  Красивый чистый код. Мне очень нравится.
У меня осталась одна проблема: я не могу понять, как получить событие, возникающее при нажатии на элемент списка последних звонков в телефоне?  В этот список попадают все мои voip вызовы, которые были осуществлены через мое приложение с использованием Вашего плагина (были зарегистрированы в CallKit).
При нажатии на сохраненный вызов просто открывается мое приложение, а мне бы хотелось инициировать в своем приложении исходящий вызов (аудио или видео, в зависимости от предыдущего вызова).

**Comment by VladimirBrejcha** [comment]
Hey @kostasoft, thank you very much for the feedback!

Following your question, this is achieved via the native code in the AppDelegate class, you would check userActivity parameter from the [application(_:continue:restorationHandler:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623072-application) method.

Voximplant has an example of this, [check it out](https://github.com/voximplant/ios-sdk-swift-demo/blob/db0c4bfd5e47abb2a16ef8e37665b5691466cbe6/AudioCallKit/AppDelegate.swift#L34)

**Comment by kostasoft** [comment]
Thank you! As always, clear and to the point!
