### ISSUE TITLE
callUUID are always uppercase

### ISSUE THREAD

**Issue by VictorUvarov** [voximplant/flutter_callkit#7]
It looks like CallKit will uppercase any UUID i send from the server. I had to lowercase all the UUIDs when sending them back to the server. 
I assume it is swift that is doing that transform. Is this correct? If so, this should probably be documented.
```swift
UUID(uuidString: callUUID)
```

**Comment by VladimirBrejcha** [comment]
Hi Victor,
Yes, Apple's NSUUID returns the uppercase uuid by default.
We will update the documentation to cover this, thanks!
