### ISSUE TITLE
Call Not Ended

### ISSUE THREAD

**Issue by Yuvarajacp** [voximplant/flutter_callkit#8]
[FlutterCallKit:ERROR > [ERROR_UNKNOWN_CALLUUID: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)]]

**Comment by YuliaGrigorieva** [comment]
Hello  @Yuvarajacp ,

The error mesaage and [CallKit error code 4](https://developer.apple.com/documentation/callkit/cxerrorcoderequesttransactionerror/code/unknowncalluuid) mean that the call UUID was incorrect. Please check that you provide correct UUID to the API.

Best regards,
Yulia Grigorieva
